### PR TITLE
Feature/crypt sshd

### PR DESCRIPTION
**Pull request by artem-sidorenko**
This is a module to allow remote unlocking of luks encrypted systems via ssh.
This module is optional and is a separate RPM package like dracut-network because of dropbear dependency (Btw dropbear is coming from EPEL on RHEL systems)

Original sources:
 - https://bugzilla.redhat.com/show_bug.cgi?id=524727#c7
 - https://github.com/mdcurtis/dracut-earlyssh
 - https://github.com/mk-fg/dracut-crypt-sshd

I spoke with all three authors ( @mk-fg , @mdcurtis and @zenczykowski ), its ok to release it under GPL2 as dracut module.

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@haraldh any steps required from me to have it merged?

**Comment by haraldh** [comment]
@artem-sidorenko : yes, squash your commits to merge fixups of your previous patches.

**Comment by artem-sidorenko** [comment]
@haraldh done, see #43

**Comment by xenoson** [comment]
It works to use systemctl:
systemctl restart cryptsetup.target
see: https://github.com/xenoson/dracut-earlyssh/tree/master/modules/60dropbear

**Pull request closed without merging**
