### PR TITLE
Revert "lvm: Don't activate LVs with activationskip set"

### PR DESCRIPTION
**Pull request by fabiand**
This reverts commit cfa365a32d47388c8476064b23d7d4684f1e591b.

### CODE REVIEW

**Comment by fabiand** [comment]
See https://github.com/haraldh/dracut/pull/75#issuecomment-115179849 .

This logic is not needed any more with newer LVMs. With newer LVMs lvchange -ay will not activate LVs with the 'k' attr.

**Comment by haraldh** [comment]
Care to add the explanation to the commit message?

**Comment by fabiand** [comment]
Yes, let me add it.

**Comment by fabiand** [comment]
Done

**Pull request merged**
